version: "3"

services:

  redis:
    image: "redis"
    ports:
      - 6379:6379

  server: 
    build: server/
    command: python ./server.py
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
